-- Add missing identity/checkin columns to agent.agents
ALTER TABLE "agent"."agents"
  ADD COLUMN IF NOT EXISTS "machine_id" text,
  ADD COLUMN IF NOT EXISTS "serial" text,
  ADD COLUMN IF NOT EXISTS "username" text,
  ADD COLUMN IF NOT EXISTS "sid" text,
  ADD COLUMN IF NOT EXISTS "last_checkin_at" timestamp with time zone;

-- Per-site enrollment token (long-standing; regenerated by MSP when needed).
-- Plaintext is never stored — only a SHA-256 hex digest.
CREATE TABLE IF NOT EXISTS "agent"."site_tokens" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "site_id" uuid NOT NULL UNIQUE REFERENCES "public"."sites"("id") ON DELETE CASCADE,
  "token_hash" text NOT NULL,
  "label" text,
  "created_by" text,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "revoked_at" timestamp with time zone
);

ALTER TABLE "agent"."site_tokens" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "crud_policy" ON "agent"."site_tokens"
  AS PERMISSIVE FOR ALL
  TO "authenticated"
  USING (true)
  WITH CHECK (true);
