import type { SchemaFields } from "../../../types/schema-registry.js";

export const M365PoliciesShape: SchemaFields = {
  name: {
    label: "Name",
    type: "string",
    modality: "single",
    trackable: true,
    ingestPath: "name",
    required: true,
  },
  description: {
    label: "Description",
    type: "string",
    modality: "single",
    trackable: false,
    ingestPath: "description",
    required: false,
  },
  state: {
    label: "State",
    type: "enum",
    modality: "single",
    trackable: true,
    ingestPath: "state",
    required: true,
    options: [
      { label: "Enabled", value: "enabled" },
      { label: "Disabled", value: "disabled" },
      { label: "Reporting Only", value: "enabledForReportingButNotEnforced" },
    ],
  },
  grantControls: {
    label: "Grant Controls",
    type: "object",
    modality: "single",
    trackable: false,
    ingestPath: "grantControls",
    required: true,
    fields: {
      operator: {
        label: "Operator",
        type: "string",
        modality: "single",
        trackable: true,
        ingestPath: "grantControls.operator",
        required: true,
      },
      builtInControls: {
        label: "Built-In Controls",
        type: "string",
        modality: "array",
        trackable: true,
        ingestPath: "grantControls.builtInControls",
        required: true,
        options: [
          { value: "block", label: "Block Sign-In" },
          { value: "mfa", label: "Require MFA" },
          { value: "compliantDevice", label: "Require Compliant Device" },
          {
            value: "domainJoinedDevice",
            label: "Require Hybrid Azure AD Join",
          },
          {
            value: "approvedApplication",
            label: "Require Approved Client App",
          },
          {
            value: "compliantApplication",
            label: "Require App Protection Policy",
          },
          { value: "passwordChange", label: "Require Password Change" },
        ],
      },
    },
  },
  sessionControls: {
    label: "Session Controls",
    type: "object",
    modality: "single",
    trackable: false,
    ingestPath: "sessionControls",
    required: false,
    fields: {
      signInFrequency: {
        label: "Sign In Frequency",
        type: "object",
        modality: "single",
        trackable: false,
        ingestPath: "sessionControls.signInFrequency",
        required: false,
        fields: {
          isEnabled: {
            label: "Enabled",
            type: "boolean",
            modality: "single",
            trackable: true,
            ingestPath: "sessionControls.signInFrequency.isEnabled",
            required: true,
          },
          type: {
            label: "Type",
            type: "enum",
            modality: "single",
            trackable: true,
            ingestPath: "sessionControls.signInFrequency.type",
            required: true,
            options: [
              { label: "Days", value: "days" },
              { label: "Hours", value: "hours" },
            ],
          },
          value: {
            label: "Value",
            type: "number",
            modality: "single",
            trackable: true,
            ingestPath: "sessionControls.signInFrequency.value",
            required: true,
          },
          frequencyInterval: {
            label: "Interval",
            type: "enum",
            modality: "single",
            trackable: true,
            ingestPath: "sessionControls.signInFrequency.frequencyInterval",
            required: true,
            options: [
              { label: "Time Based", value: "timeBased" },
              { label: "Every Time", value: "everyTime" },
            ],
          },
        },
      },
      persistentBrowser: {
        label: "Persistent Browser",
        type: "object",
        modality: "single",
        trackable: false,
        ingestPath: "sessionControls.persistentBrowser",
        required: false,
        fields: {
          mode: {
            label: "Mode",
            type: "enum",
            modality: "single",
            trackable: true,
            ingestPath: "sessionControls.persistentBrowser.mode",
            required: false,
            options: [
              { label: "Always", value: "always" },
              { label: "Never", value: "never" },
            ],
          },
          isEnabled: {
            label: "Enabled",
            type: "boolean",
            modality: "single",
            trackable: true,
            ingestPath: "sessionControls.persistentBrowser.isEnabled",
            required: true,
          },
        },
      },
    },
  },
  conditions: {
    label: "Conditions",
    type: "object",
    modality: "single",
    trackable: false,
    ingestPath: "conditions",
    required: true,
    fields: {
      users: {
        label: "Users",
        type: "object",
        modality: "single",
        trackable: false,
        ingestPath: "conditions.users",
        required: true,
        fields: {
          includeUsers: {
            label: "Include Users",
            type: "string",
            modality: "array",
            trackable: true,
            ingestPath: "conditions.users.includeUsers",
            required: true,
            options: [{ value: "All", label: "All Users" }],
          },
          excludeUsers: {
            label: "Exclude Users",
            type: "string",
            modality: "array",
            trackable: false,
            ingestPath: "conditions.users.excludeUsers",
            required: false,
            reference: {
              table: "m365Identities",
              valueColumn: "externalId",
              labelColumn: "name",
              specialValues: [
                {
                  value: "GuestsOrExternalUsers",
                  label: "Guests / External Users",
                },
              ],
            },
          },
          includeGroups: {
            label: "Include Groups",
            type: "string",
            modality: "array",
            trackable: false,
            ingestPath: "conditions.users.includeGroups",
            required: false,
            reference: {
              table: "m365Groups",
              valueColumn: "externalId",
              labelColumn: "name",
            },
          },
          excludeGroups: {
            label: "Exclude Groups",
            type: "string",
            modality: "array",
            trackable: false,
            ingestPath: "conditions.users.excludeGroups",
            required: false,
            reference: {
              table: "m365Groups",
              valueColumn: "externalId",
              labelColumn: "name",
            },
          },
          includeRoles: {
            label: "Include Roles",
            type: "string",
            modality: "array",
            trackable: true,
            ingestPath: "conditions.users.includeRoles",
            required: false,
            reference: {
              table: "m365Roles",
              valueColumn: "templateId",
              labelColumn: "name",
            },
          },
          excludeRoles: {
            label: "Exclude Roles",
            type: "string",
            modality: "array",
            trackable: false,
            ingestPath: "conditions.users.excludeRoles",
            required: false,
          },
        },
      },
      applications: {
        label: "Applications",
        type: "object",
        modality: "single",
        trackable: false,
        ingestPath: "conditions.applications",
        required: true,
        fields: {
          includeApplications: {
            label: "Include Applications",
            type: "string",
            modality: "array",
            trackable: true,
            ingestPath: "conditions.applications.includeApplications",
            required: true,
            options: [{ label: "All", value: "All" }],
          },
          excludeApplications: {
            label: "Exclude Applications",
            type: "string",
            modality: "array",
            trackable: false,
            ingestPath: "conditions.applications.excludeApplications",
            required: false,
          },
          includeUserActions: {
            label: "Include User Actions",
            type: "string",
            modality: "array",
            trackable: false,
            ingestPath: "conditions.applications.includeUserActions",
            required: false,
            options: [
              { label: "Register Device", value: "urn:user:registerdevice" },
            ],
          },
        },
      },
      clientAppTypes: {
        label: "Client App Types",
        type: "string",
        modality: "array",
        trackable: true,
        ingestPath: "conditions.clientAppTypes",
        required: false,
        options: [
          {
            label: "Mobile Apps and Desktop Clients",
            value: "mobileAppsAndDesktopClients",
          },
          { label: "Exchange Active Sync", value: "exchangeActiveSync" },
          { label: "Browser", value: "browser" },
          { label: "Other", value: "other" },
        ],
      },
      userRiskLevels: {
        label: "User Risk Levels",
        type: "string",
        modality: "array",
        trackable: true,
        ingestPath: "conditions.userRiskLevels",
        required: false,
      },
      signInRiskLevels: {
        label: "Sign-in Risk Levels",
        type: "string",
        modality: "array",
        trackable: true,
        ingestPath: "conditions.signInRiskLevels",
        required: false,
      },
      locations: {
        label: "Locations",
        type: "object",
        modality: "single",
        trackable: false,
        ingestPath: "conditions.locations",
        required: false,
        fields: {
          includeLocations: {
            label: "Include Locations",
            type: "string",
            modality: "array",
            trackable: true,
            ingestPath: "conditions.locations.includeLocations",
            required: true,
            options: [{ label: "All", value: "All" }],
          },
          excludeLocations: {
            label: "Exclude Locations",
            type: "string",
            modality: "array",
            trackable: false,
            ingestPath: "conditions.locations.excludeLocations",
            required: false,
          },
        },
      },
      platforms: {
        label: "Platforms",
        type: "object",
        modality: "single",
        trackable: false,
        ingestPath: "conditions.platforms",
        required: false,
        fields: {
          includePlatforms: {
            label: "Include Platforms",
            type: "string",
            modality: "array",
            trackable: true,
            ingestPath: "conditions.platforms.includePlatforms",
            required: true,
            options: [
              { label: "Windows", value: "windows" },
              { label: "MacOS", value: "macOS" },
              { label: "Linux", value: "linux" },
              { label: "Android", value: "android" },
              { label: "iOS", value: "iOS" },
              { label: "Windows Phone", value: "windowsPhone" },
            ],
          },
          excludePlatforms: {
            label: "Exclude Platforms",
            type: "string",
            modality: "array",
            trackable: true,
            ingestPath: "conditions.platforms.excludePlatforms",
            required: false,
            options: [
              { label: "Windows", value: "windows" },
              { label: "MacOS", value: "macOS" },
              { label: "Linux", value: "linux" },
              { label: "Android", value: "android" },
              { label: "iOS", value: "iOS" },
              { label: "Windows Phone", value: "windowsPhone" },
            ],
          },
        },
      },
    },
  },
};
