/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignoutRouteImport } from './routes/auth/signout'
import { Route as AuthOrganizationRouteImport } from './routes/auth/organization'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ProtectedSitesRouteImport } from './routes/_protected/sites'
import { Route as ProtectedSetupRouteImport } from './routes/_protected/setup'
import { Route as ProtectedHomeRouteImport } from './routes/_protected/home'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedSitesSiteIdRouteImport } from './routes/_protected/sites.$siteId'
import { Route as ProtectedSetupUsersRouteImport } from './routes/_protected/setup.users'
import { Route as ProtectedSetupPipelineRouteImport } from './routes/_protected/setup.pipeline'
import { Route as ProtectedSetupIntegrationsRouteImport } from './routes/_protected/setup.integrations'
import { Route as ProtectedSetupAuditRouteImport } from './routes/_protected/setup.audit'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignoutRoute = AuthSignoutRouteImport.update({
  id: '/auth/signout',
  path: '/auth/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOrganizationRoute = AuthOrganizationRouteImport.update({
  id: '/auth/organization',
  path: '/auth/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSitesRoute = ProtectedSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSetupRoute = ProtectedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHomeRoute = ProtectedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSitesSiteIdRoute = ProtectedSitesSiteIdRouteImport.update({
  id: '/$siteId',
  path: '/$siteId',
  getParentRoute: () => ProtectedSitesRoute,
} as any)
const ProtectedSetupUsersRoute = ProtectedSetupUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ProtectedSetupRoute,
} as any)
const ProtectedSetupPipelineRoute = ProtectedSetupPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => ProtectedSetupRoute,
} as any)
const ProtectedSetupIntegrationsRoute =
  ProtectedSetupIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => ProtectedSetupRoute,
  } as any)
const ProtectedSetupAuditRoute = ProtectedSetupAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ProtectedSetupRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof ProtectedHomeRoute
  '/setup': typeof ProtectedSetupRouteWithChildren
  '/sites': typeof ProtectedSitesRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/organization': typeof AuthOrganizationRoute
  '/auth/signout': typeof AuthSignoutRoute
  '/setup/audit': typeof ProtectedSetupAuditRoute
  '/setup/integrations': typeof ProtectedSetupIntegrationsRoute
  '/setup/pipeline': typeof ProtectedSetupPipelineRoute
  '/setup/users': typeof ProtectedSetupUsersRoute
  '/sites/$siteId': typeof ProtectedSitesSiteIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof ProtectedHomeRoute
  '/setup': typeof ProtectedSetupRouteWithChildren
  '/sites': typeof ProtectedSitesRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/organization': typeof AuthOrganizationRoute
  '/auth/signout': typeof AuthSignoutRoute
  '/setup/audit': typeof ProtectedSetupAuditRoute
  '/setup/integrations': typeof ProtectedSetupIntegrationsRoute
  '/setup/pipeline': typeof ProtectedSetupPipelineRoute
  '/setup/users': typeof ProtectedSetupUsersRoute
  '/sites/$siteId': typeof ProtectedSitesSiteIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/home': typeof ProtectedHomeRoute
  '/_protected/setup': typeof ProtectedSetupRouteWithChildren
  '/_protected/sites': typeof ProtectedSitesRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/organization': typeof AuthOrganizationRoute
  '/auth/signout': typeof AuthSignoutRoute
  '/_protected/setup/audit': typeof ProtectedSetupAuditRoute
  '/_protected/setup/integrations': typeof ProtectedSetupIntegrationsRoute
  '/_protected/setup/pipeline': typeof ProtectedSetupPipelineRoute
  '/_protected/setup/users': typeof ProtectedSetupUsersRoute
  '/_protected/sites/$siteId': typeof ProtectedSitesSiteIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/setup'
    | '/sites'
    | '/auth/login'
    | '/auth/organization'
    | '/auth/signout'
    | '/setup/audit'
    | '/setup/integrations'
    | '/setup/pipeline'
    | '/setup/users'
    | '/sites/$siteId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/setup'
    | '/sites'
    | '/auth/login'
    | '/auth/organization'
    | '/auth/signout'
    | '/setup/audit'
    | '/setup/integrations'
    | '/setup/pipeline'
    | '/setup/users'
    | '/sites/$siteId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/home'
    | '/_protected/setup'
    | '/_protected/sites'
    | '/auth/login'
    | '/auth/organization'
    | '/auth/signout'
    | '/_protected/setup/audit'
    | '/_protected/setup/integrations'
    | '/_protected/setup/pipeline'
    | '/_protected/setup/users'
    | '/_protected/sites/$siteId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOrganizationRoute: typeof AuthOrganizationRoute
  AuthSignoutRoute: typeof AuthSignoutRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signout': {
      id: '/auth/signout'
      path: '/auth/signout'
      fullPath: '/auth/signout'
      preLoaderRoute: typeof AuthSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/organization': {
      id: '/auth/organization'
      path: '/auth/organization'
      fullPath: '/auth/organization'
      preLoaderRoute: typeof AuthOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/sites': {
      id: '/_protected/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof ProtectedSitesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/setup': {
      id: '/_protected/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof ProtectedSetupRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/home': {
      id: '/_protected/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedHomeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/sites/$siteId': {
      id: '/_protected/sites/$siteId'
      path: '/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof ProtectedSitesSiteIdRouteImport
      parentRoute: typeof ProtectedSitesRoute
    }
    '/_protected/setup/users': {
      id: '/_protected/setup/users'
      path: '/users'
      fullPath: '/setup/users'
      preLoaderRoute: typeof ProtectedSetupUsersRouteImport
      parentRoute: typeof ProtectedSetupRoute
    }
    '/_protected/setup/pipeline': {
      id: '/_protected/setup/pipeline'
      path: '/pipeline'
      fullPath: '/setup/pipeline'
      preLoaderRoute: typeof ProtectedSetupPipelineRouteImport
      parentRoute: typeof ProtectedSetupRoute
    }
    '/_protected/setup/integrations': {
      id: '/_protected/setup/integrations'
      path: '/integrations'
      fullPath: '/setup/integrations'
      preLoaderRoute: typeof ProtectedSetupIntegrationsRouteImport
      parentRoute: typeof ProtectedSetupRoute
    }
    '/_protected/setup/audit': {
      id: '/_protected/setup/audit'
      path: '/audit'
      fullPath: '/setup/audit'
      preLoaderRoute: typeof ProtectedSetupAuditRouteImport
      parentRoute: typeof ProtectedSetupRoute
    }
  }
}

interface ProtectedSetupRouteChildren {
  ProtectedSetupAuditRoute: typeof ProtectedSetupAuditRoute
  ProtectedSetupIntegrationsRoute: typeof ProtectedSetupIntegrationsRoute
  ProtectedSetupPipelineRoute: typeof ProtectedSetupPipelineRoute
  ProtectedSetupUsersRoute: typeof ProtectedSetupUsersRoute
}

const ProtectedSetupRouteChildren: ProtectedSetupRouteChildren = {
  ProtectedSetupAuditRoute: ProtectedSetupAuditRoute,
  ProtectedSetupIntegrationsRoute: ProtectedSetupIntegrationsRoute,
  ProtectedSetupPipelineRoute: ProtectedSetupPipelineRoute,
  ProtectedSetupUsersRoute: ProtectedSetupUsersRoute,
}

const ProtectedSetupRouteWithChildren = ProtectedSetupRoute._addFileChildren(
  ProtectedSetupRouteChildren,
)

interface ProtectedSitesRouteChildren {
  ProtectedSitesSiteIdRoute: typeof ProtectedSitesSiteIdRoute
}

const ProtectedSitesRouteChildren: ProtectedSitesRouteChildren = {
  ProtectedSitesSiteIdRoute: ProtectedSitesSiteIdRoute,
}

const ProtectedSitesRouteWithChildren = ProtectedSitesRoute._addFileChildren(
  ProtectedSitesRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedHomeRoute: typeof ProtectedHomeRoute
  ProtectedSetupRoute: typeof ProtectedSetupRouteWithChildren
  ProtectedSitesRoute: typeof ProtectedSitesRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedHomeRoute: ProtectedHomeRoute,
  ProtectedSetupRoute: ProtectedSetupRouteWithChildren,
  ProtectedSitesRoute: ProtectedSitesRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthOrganizationRoute: AuthOrganizationRoute,
  AuthSignoutRoute: AuthSignoutRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
